---
- hosts: "{{hosts}}"
  vars:
  - repo: git@github.com:dperezrada/crypto_market_quotes.git
  - repo_name: crypto_market_quotes
  - environment_path: /home/deploy/envs/pydev
  - home_path: /home/deploy
  - repos_root: /home/deploy/repos
  - project_branch: master
  - requirements_file: "{{repos_root}}/{{repo_name}}/requirements.txt"


  tasks:
  - name: Pull sources from the repository.
    git: repo={{ repo }} dest={{ repos_root }}/{{repo_name}} version={{ project_branch|default("master") }} accept_hostkey=yes
  - name: Copy authkeys
    copy: src=authkeys.yml dest={{ repos_root }}/{{repo_name}}/authkeys.yml owner=deploy group=deploy mode=0600
  - name: Change owner to deploy
    file: path={{ repos_root }}/{{repo_name}} owner=deploy group=deploy recurse=yes

  - name: Install requirements
    shell: "{{environment_path}}/bin/pip install --upgrade --force-reinstall -r {{requirements_file}}"

  - name: Install package
    shell: "cd {{ repos_root }}/{{repo_name}};{{environment_path}}/bin/python setup.py develop"

  - name: Setting crontab for each exchange bid_ask
    cron: name="calculate exchange {{ item.exchange }} bid_ask" hour="*" minute="{{ item.minute }}" user="deploy" job="mkdir -p /home/deploy/data/bid_ask/{{ item.exchange }}/$(date +\\%Y-\\%m-\\%d); /home/deploy/envs/pydev/bin/python3.6 /home/deploy/repos/crypto_market_quotes/crypto_market_quotes/main.py -e {{ item.exchange }} bid_ask >> /home/deploy/data/bid_ask/{{ item.exchange }}/$(date +\\%Y-\\%m-\\%d)/$(date +\\%H).log 2>> {{ home_path }}/logs/bid_ask_{{ item.exchange }}.log"
    with_items:
      - { minute: '*', exchange: 'bitfinex' }
      - { minute: '*', exchange: 'surbtc' }
      - { minute: '*', exchange: 'kraken' }
      - { minute: '*', exchange: 'cryptomkt' }

  - name: Setting crontab for currency_rates
    cron: name="calculate currency_rates" hour="*" minute="*" user="deploy" job="mkdir -p /home/deploy/data/currency_rates/$(date +\\%Y-\\%m-\\%d); /home/deploy/envs/pydev/bin/python3.6 /home/deploy/repos/crypto_market_quotes/crypto_market_quotes/main.py currency_rates >> /home/deploy/data/currency_rates/$(date +\\%Y-\\%m-\\%d)/$(date +\\%H).log 2>> {{ home_path }}/logs/currency_rates.log"

  - name: Setting crontab for trades
    cron: name="calculate trades" hour="*" minute="*/5" user="deploy" job="mkdir -p /home/deploy/data/trades/surbtc/$(date +\\%Y-\\%m-\\%d); /home/deploy/envs/pydev/bin/python3.6 /home/deploy/repos/crypto_market_quotes/crypto_market_quotes/main.py trades -e surbtc >> /home/deploy/data/trades/surbtc/$(date +\\%Y-\\%m-\\%d)/$(date +\\%H).log 2>> {{ home_path }}/logs/trades_surbtc.log"