---
# Mainly from: https://github.com/phred/5minbootstrap/blob/master/bootstrap.yml
- hosts: "{{hosts}}"
  vars:
  - ubuntu_release: artful #precise,trusty,etc
  - deploy_password: 'aurhtSmEJzOKn1MbUyUpFV6cl61mHHES'
  - base_home: /home/dperezrada
  - deploy_home: /home/deploy
  - environment_path: /home/deploy/envs/pydev

  tasks:
  - name: Update APT package cache
    apt: update_cache=yes

  - name: Run apt-get upgrade
    apt: upgrade=yes

  - name: Add deployment user
    user: name=deploy password=$deploy_password shell=/bin/bash

  - name: Creates deploy .ssh directory
    file: path={{deploy_home}}/.ssh state=directory owner=deploy group=deploy mode=0700

  - name: Copy authorized_keys file
    command: creates="{{deploy_home}}/.ssh/authorized_keys" cp {{base_home}}/.ssh/authorized_keys {{deploy_home}}/.ssh/authorized_keys

  - name: Set deploy authorized_keys permissions
    file: path={{deploy_home}}/.ssh/authorized_keys state=file owner=deploy group=deploy mode=0600

  - name: Disallow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present

  - name: Create logs directory
    file: path=/home/deploy/logs state=directory mode=0755 owner=deploy group=deploy

  - name: Create repos directory
    file: path=/home/deploy/repos state=directory mode=0755 owner=deploy group=deploy

  - name: Install unattended-upgrades
    apt: pkg=unattended-upgrades state=present

  - name: Adjust APT update intervals
    copy:
      content: 'APT::Periodic::Update-Package-Lists "1";APT::Periodic::Download-Upgradeable-Packages "1";APT::Periodic::AutocleanInterval "7";APT::Periodic::Unattended-Upgrade "1";'
      dest: /etc/apt/apt.conf.d/10periodic

  - name: Make sure unattended-upgrades only installs from $ubuntu_release-security
    lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

  - name: Install dependencies
    apt: name={{ item }} state=installed update-cache=yes
    with_items:
      - git-core
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev

  - name: install various libraries with pip
    action: pip name={{item}} state=present executable=pip3
    with_items:
      - virtualenv

  - name: create virtualenv
    command: virtualenv {{environment_path}} -p python3.6 creates={{environment_path}}
    become: yes
    become_user: deploy

  - name: Add ssh agent line to sudoers
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: SSH_AUTH_SOCK
      line: Defaults env_keep += "SSH_AUTH_SOCK"

  - name: ensure github.com is a known host
    lineinfile:
      dest: /root/.ssh/known_hosts
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
      regexp: "^github\\.com"
